name: ci docker

on:
  push:
    branches: [ master, development ]
    paths:
      - "!README.md"
  pull_request:
    branches: [ master, development ]
    paths:
      - "!README.md"
      
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-20.04
    env:
      DOCKER_IMAGE: DOCKER_IMAGE
      DOCKER_TAG: DOCKER_TAG

    steps:
      - uses: actions/checkout@v2
      - name: Build docker
      - run: docker-compose -f infrastructure/docker-compose.build.yml build
