name: CI data collector

# TODO replace DATA_COLLECTOR with correct dc directory name

on:
  push:
    branches: [ development, master ]
  pull_request:
    branches: [ development, master ]
  
  paths:
    - "data-collectors/DATA_COLLECTOR"
    # prevent building on documentation changes
    - "!README.md"
    - "!data-collectors/DATA_COLLECTOR/README.md"


  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
          cache: maven

      - name: Test with Maven
        run: mvn -B -U clean compile test
