name: ci npm

on:
  push:
    branches: [ master, development ]
    paths:
      - "!README.md"
  pull_request:
    branches: [ master, development ]
    paths:
      - "!README.md"
      
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '12'
          cache: 'npm'
      - name: install
        run: npm install
      - name: test
        run: npm test

      # used in many webcomps
      # - name: REUSE Compliance Check
      #   uses: fsfe/reuse-action@v1
