name: NOI Organization CI

on:
  push:
    branches: [ $default-branch ]
  pull_request:
    branches: [ $default-branch ]
  
  paths:
    - "*"
    # prevent building on documentation changes
    - "!README.md"


  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2

      - name: Run a one-line script
        run: echo Hello from NOI Techpark
